// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "blocsy/internal/types"
)

func main() {
  g := gen.NewGenerator("sol_easyjson.go")
  g.SetPkg("types", "blocsy/internal/types")
  g.Add(pkg.EasyJSON_exporter_AccountKey(nil))
  g.Add(pkg.EasyJSON_exporter_AddressTableLookup(nil))
  g.Add(pkg.EasyJSON_exporter_BlockData(nil))
  g.Add(pkg.EasyJSON_exporter_BlockResult(nil))
  g.Add(pkg.EasyJSON_exporter_HTTPBlockMessage(nil))
  g.Add(pkg.EasyJSON_exporter_HTTPTxMessage(nil))
  g.Add(pkg.EasyJSON_exporter_InnerInstruction(nil))
  g.Add(pkg.EasyJSON_exporter_InnerSwap(nil))
  g.Add(pkg.EasyJSON_exporter_Instruction(nil))
  g.Add(pkg.EasyJSON_exporter_LoadedAddresses(nil))
  g.Add(pkg.EasyJSON_exporter_LogDetails(nil))
  g.Add(pkg.EasyJSON_exporter_Message(nil))
  g.Add(pkg.EasyJSON_exporter_MetaplexData(nil))
  g.Add(pkg.EasyJSON_exporter_MetaplexMetadata(nil))
  g.Add(pkg.EasyJSON_exporter_MetaplexMetadataData(nil))
  g.Add(pkg.EasyJSON_exporter_NativeInOutData(nil))
  g.Add(pkg.EasyJSON_exporter_ParsedDataInfo(nil))
  g.Add(pkg.EasyJSON_exporter_PoolInit(nil))
  g.Add(pkg.EasyJSON_exporter_RaySwapLog(nil))
  g.Add(pkg.EasyJSON_exporter_SolBalanceDiff(nil))
  g.Add(pkg.EasyJSON_exporter_SolSwap(nil))
  g.Add(pkg.EasyJSON_exporter_SolSwapData(nil))
  g.Add(pkg.EasyJSON_exporter_SolTransfer(nil))
  g.Add(pkg.EasyJSON_exporter_SolanaBlockTx(nil))
  g.Add(pkg.EasyJSON_exporter_SolanaTx(nil))
  g.Add(pkg.EasyJSON_exporter_SwapBaseInLog(nil))
  g.Add(pkg.EasyJSON_exporter_SwapBaseOutLog(nil))
  g.Add(pkg.EasyJSON_exporter_SystemProgramData(nil))
  g.Add(pkg.EasyJSON_exporter_TokenBalance(nil))
  g.Add(pkg.EasyJSON_exporter_TokenInOutData(nil))
  g.Add(pkg.EasyJSON_exporter_TokenProgramData(nil))
  g.Add(pkg.EasyJSON_exporter_TransactionData(nil))
  g.Add(pkg.EasyJSON_exporter_TransactionError(nil))
  g.Add(pkg.EasyJSON_exporter_TransactionMeta(nil))
  g.Add(pkg.EasyJSON_exporter_TransactionStatus(nil))
  g.Add(pkg.EasyJSON_exporter_UITokenAmount(nil))
  g.Add(pkg.EasyJSON_exporter_WSBlockMessage(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
