FROM golang:1.23.5-alpine3.19 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

ENV APP_ENV=production

WORKDIR /app/cmd/api
RUN swag fmt && swag init --parseDependency --parseInternal

WORKDIR /app

RUN go build -o app ./cmd/api/main.go

FROM alpine:3.19

WORKDIR /app

# Install curl
RUN apk add --no-cache curl

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]