FROM golang:1.22.2-alpine3.19 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV APP_ENV=production

RUN go build -o app ./cmd/listener/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/app .


CMD ["./app"]