FROM golang:1.23-alpine3.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV APP_ENV=production

RUN go build -o app ./cmd/txProcessor/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8081

CMD ["./app"]