name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd blocsy
            git pull

#            REBUILD ALL CONTAINERS
            sudo docker-compose down
            docker system prune -a -f
            sudo docker-compose up -d --build

#            ONLY REDO THE API CONTAINER
#            sudo docker-compose build api
#            sudo docker-compose up -d --no-deps --build api
