name: Deploy Backfill

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH and Deploy to EC2 (API Only)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd blocsy
            git pull

            # Rebuild only the Backfill container
            sudo docker-compose build backfill
            sudo docker-compose up -d --no-deps --build backfill
